name: Deploy Cloudflare Worker

on:
  workflow_dispatch:
  push:
    branches: [ main, master ]
    paths:
      - 'src/**'
      - 'wrangler.toml'
      - 'package.json'

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: |
          npm ci || npm i --no-audit --no-fund

      - name: Publish with Wrangler
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
        run: |
          npx wrangler deploy --verbose
